# base image
FROM node:14.16.1-alpine as build

# build environment
ENV NODE_ENV production

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --only=production --silent 
RUN npm install react-scripts@3.4.1 -g --silent
COPY . ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 3015
CMD ["nginx", "-g", "daemon off;"]